AWSTemplateFormatVersion: "2010-09-09"
Description: Service resources

Parameters:
  EnvLabel:
    Description: Name of the environment this cloudformation stack belongs to
    Type: String

  EnvType:
    Default: nonproduction
    Description: Type of the environment for this stack
    Type: String
    AllowedValues:
      - nonproduction
      - production
  # NOTE: this needs to be lower case as repository name does not take upper case

  SubSystem:
    Type: String
    Description: Subsystem Code (should be all lowercases)
    AllowedPattern: "^[a-z]+$"

  ServiceName:
    Type: String
    Description: Name of the service under particular subsystem

Resources: 
  WorkerWebAppRepo: 
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: "worker-web-app"
Outputs:    
  WorkerWebAppArn:
    Value: !GetAtt WorkerWebAppRepo.Arn
    Export: 
      Name: WorkerWebAppArn
      
